name: Run SmartBugs
on: [push]
jobs:
  run-smartbugs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tool: ["slither"]
        #contract: ["'samples/simple_dao.*'"]
        python-version: ["3.6.9"]
        #python-version: ["3.10.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: git clone https://github.com/smartbugs/smartbugs.git; cd smartbugs; git checkout sb2.0; ./setup-venv.sh
      - name: Execute ${{ matrix.tool }} on ${{ matrix.contract }}
        run: source venv/bin/activate; ./smartbugs -t ${{ matrix.tool }} -f *.sol --sarif --runid github
      - name: Upload SARIF file for slither, mode sol
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results/slither/github/simple_dao.sol/result.sarif
          category: slither/sol
