name: Run SmartBugs
on: [push]
jobs:
  run-smartbugs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        #tools: ["slither", "mythril"]
        tools: ["slither"]
        python-version: ["3.6.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup
        run: git clone https://github.com/smartbugs/smartbugs.git; cd smartbugs; git checkout sb2.0; ./setup-venv.sh

      - name: Execute ${{ matrix.tools }}
        run: cd smartbugs; source venv/bin/activate; ./smartbugs -t ${{ matrix.tools }} -f ../*.sol --sarif --runid github; find results

      - name: Upload SARIF file for slither, mode sol
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: smartbugs/results/${{ matrix.tools }}/github/simple_dao.sol/result.sarif
          category: ${{ matrix.tools }}/sol
